on: push

name: Test comment

jobs:
  test-comment:
    name: Comment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: adjust/gajira-login@v4
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Comment on issue
      uses: ./
      with:
        issue: FPLAT-410
        comment: Test comment ${{ github.event.compare }} # https://developer.github.com/v3/activity/events/types/#webhook-payload-example-31
